### ISSUE TITLE
aggressive spider log useless info...

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2106]
with the spider log on aggressive it should tell you what topic the spider has viewed

instead it is showing stuff like this...

```
a:4:{s:5:"topic";i:37;s:9:"prev_next";s:4:"prev";s:5:"board";i:1;s:10:"USER_AGENT";s:72:"Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)";}
```

**Comment by illori** [comment]
Notice: Undefined index: viewing in F:\wamp\www\github2.1\Sources\ManageSearchEngines.php on line 788

**Comment by NanoSector** [comment]
Something is going wrong when serializing the data, Illori gave me a copy of her database table.

```
Notice: unserialize(): Error at offset 89 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 58 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 58 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 58 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 68 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 58 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 58 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 57 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309

Notice: unserialize(): Error at offset 89 of 255 bytes in /mnt/data/Web/smf21/Sources/Who.php on line 309
```

**Comment by NanoSector** [comment]
Looks like it's fixed in the meantime somewhere. There's one trick I can apply and that's encoding the variable, to make sure different servers interpret it correctly and MySQL doesn't screw with it.

**Comment by Oldiesmann** [comment]
Running it through base64_encode won't fix problems caused by unexpected characters in the serialized string or other weirdness.

**Comment by Oldiesmann** [comment]
Illori, is this still an issue for you? If so, can you provide a copy of the data? I'm unable to reproduce this on my Archie forum (note that it's 2.0, but the code for this functionality appears to be the same in 2.0 and 2.1, and my 2.1 board won't get me near-instant data like my Archie forum will). The only issue I had there was that a couple of the serialized strings were too long for the database.

**Comment by illori** [comment]
this did not fix the issue. in firefox using the user agent switcher and logging out of the forum you can get some spider hits. these hits still have the garbage showing up in the url view

![](http://imagizer.imageshack.us/v2/842x238q90/540/oCIEcG.png)

**Comment by illori** [comment]
on one of my 2.0 forums, it has a similar issue that 2.1 is showing.

```
a:4:{s:6:"action";s:5:"media";s:2:"sa";s:4:"item";s:2:"in";s:3:"476";s:10:"USER_AGENT";s:169:"SAMSUNG-SGH-E250/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Browser/6.2.3.3.c.1.101 (GUI) MMP/2.0 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/b
```

but in 2.1 it is not logging the location that the spider was crawling, where that one from 2.0 shows that the spider was in the media gallery.
