### ISSUE TITLE
WYSIWYG editor: links are messed up

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#3102]
As per
http://www.simplemachines.org/community/index.php?topic=540636.0

When adding a link using the WYSIWYG editor, the links are messed up. Eg:
http://"http//www.google.pt

The topic at sm.org mentions https links but in my test board it seems to break any link

**Comment by Oldiesmann** [comment]
On my test board links seem to work fine whether it has https or not, but it's using the iurl tag instead of the regular one.

**Comment by margarett** [comment]
You need to use the "Insert a link" button (so you can't choose which tag is being used)

**Comment by Oldiesmann** [comment]
I am using the "Insert a link" button.

This seems to be the relevant code causing it:

``` javascript
            if (element.attr('target') !== undefined)
                return '[url=' + decodeURI(url) + ']' + content + '[/url]';
            else
                return '[iurl=' + decodeURI(url) + ']' + content + '[/iurl]';
```

**Comment by Oldiesmann** [comment]
It uses iurl if I'm in WYSIWYG mode but the regular url tag if I'm not.

**Comment by margarett** [comment]
Yes, you're right, sorry.

This is what I get (editing the message in "source" mode)
[iurl="http://\"https://www.google.pt/?gws_rd=ssl""]https://www.google.pt/?gws_rd=ssl[/iurl]

**Comment by margarett** [comment]
FWIW, the "demo" at sceditor.com doesn't seem to support "iurl"? Maybe there's the problem?

edit: Oldies, you need to post in order to see the issue. If you just toggle in and out of WYSIWYG the link is fine ;)

edit2: this is what goes into the database:

```
[iurl=http://&quot;https://www.google.pt/?gws_rd=ssl&quot;]https://www.google.pt/?gws_rd=ssl[/iurl]
```

So it's something which happens when submitting the post? It seems that it's forcing HTTP into the URL

edit3: :tada: 
Got it! In WYSIWYG mode, the editor wraps the URL in quotes. That's what messes the links!

edit4: (dang this is getting annoying :tongue: )
It only wraps _some_ links in quotes. Eg:
http://www.google.pt is fine
https://www.google.pt/?gws_rd=ssl is wrapped in quotes and, therefore, screwed. :open_mouth:

**Comment by Oldiesmann** [comment]
I have no idea why it's doing that. Either way it still shouldn't be using the iurl tag like that...

**Comment by margarett** [comment]
That I can tell you ;)

```
            if (element.attr('target') !== undefined)
                return '[url=' + decodeURI(url) + ']' + content + '[/url]';
            else
                return '[iurl=' + decodeURI(url) + ']' + content + '[/iurl]';
```

(not that I know what that means :tongue: )

Now a funny detail. Remove that and leave just the "return '[url=.......". The problem with the messed links and excessive double quotes is fixed. Eh :stuck_out_tongue: 

edit: not totally fixed. The editor now uses url instead of iurl but, if you manually use iurl, the link still gets messed up...

edit2: 
That change, however, causes the WYSIWYG editor not support iurl properly. If I enter (in Source mode)

```
[iurl=https://www.google.pt/?gws_rd=ssl]https://www.google.pt/?gws_rd=ssl[/iurl]
```

Then go to WYSIWYG, then back to Source, the iurl is now a url :confused:

**Comment by Oldiesmann** [comment]
That code seems to be looking for a "target" attribute of the anchor tag, then returning either url or iurl depending on whether it's set (the difference is that links with iurl open in the same tab/window while ones with regular url don't). Still doesn't make any sense though.

**Comment by Oldiesmann** [comment]
Figured out what was causing the links to get converted to iurl. Basically, the HTML code that was being generated for inserted links lacked the "target" attribute. Committed a fix for it with 918db8e76477236fb3f5c8369bdcc66e717b523b. Still looking into the issue with quotes being inserted around some links.

**Comment by Oldiesmann** [comment]
Finally got to the bottom of the quoted URLs issue. We need to specify `quoteType: $.scEditor.BBCodeParser.quoteType.never` for both the iurl and url tags in jquery.sceditor.smf.js.
