### ISSUE TITLE
errors after banning

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4618]
Notice
: Undefined index: reported_members in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4412

Notice
: Undefined index: title in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4412

this user was banned and now has logged into the forum after being logged out... the above errors showed in the header after the user logged in.
after refreshing the page the errors did NOT go away

also this member did not show up in the members list [public one] until after the user logged in even though the ban had expired.

**Comment by illori** [comment]
error log has the following

Type of error: Undefined 							 							8: Undefined index: href 							 							http://localhost:8080/github2.1/index.php?  							 													 D:/wamp/www/github2.1/Themes/default/index.template.php (Line 512) |

test 							 							Today at 06:23 am 							 							::1 							 							 							85b15b18814b1c8bb3e3e24e93d0f616 						 						 							 							Type of error: Undefined 							 							8: Undefined index: title 							 							http://localhost:8080/github2.1/index.php?  							 													 D:/wamp/www/github2.1/Sources/Subs.php (Line 4412) |  
test 							 							Today at 06:23 am 							 							::1 							 							 							85b15b18814b1c8bb3e3e24e93d0f616 						 						 							 							Type of error: Undefined 							 							8: Undefined index: reported_members 							 							http://localhost:8080/github2.1/index.php?  							 													 D:/wamp/www/github2.1/Sources/Subs.php (Line 4412)

**Comment by albertlast** [comment]
Since the line of code did change,
but i think the issue get fixed by this pr: https://github.com/SimpleMachines/SMF2.1/pull/4660

**Comment by illori** [comment]
not this error has not been resolved by that PR.

Type of error: Undefined
8: Undefined index: href http://localhost:8080/github2.1/index.php?http://localhost:8080/github2.1/
D:/wamp/www/github2.1/Themes/default/index.template.php (Line 512) 
	Type of error: Undefined
8: Undefined index: title http://localhost:8080/github2.1/index.php?http://localhost:8080/github2.1/
D:/wamp/www/github2.1/Sources/Subs.php (Line 4501) 
 Type of error: Undefined
8: Undefined index: reported_members http://localhost:8080/github2.1/index.php?http://localhost:8080/github2.1/
D:/wamp/www/github2.1/Sources/Subs.php (Line 4501)

**Comment by albertlast** [comment]
Could you please paste your Subs.php?

**Comment by illori** [comment]
I just updated to the latest version to double check before I made that
reply that this is still happening.

**Comment by albertlast** [comment]
Reason why i ask in line 4998 we got the the check
```
!empty($context['menu_buttons']['moderate']['sub_buttons']['reported_members'])
```
So i don't understand why this should be true without existing...

https://github.com/SimpleMachines/SMF2.1/blob/e3cf3713359514549bf9d9c98fcb6b65035513be/Sources/Subs.php#L4498-L4502

**Comment by illori** [comment]
i dont know what changed but i opened the forum again and the errors are gone.
