### ISSUE TITLE
Gender not showing anywhere,

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5373]
Might just be me doing something stupid, but I can't get the Gender to display anywhere on my test site.  Unless I'm missing a setting somewhere it appears to be broken.

Confirmation please.

**Comment by smfbigguy** [comment]
I can confirm this. It used to show on my site. It is not there now for some reason.

**Comment by MissAllSunday** [comment]
If you inspect the page where the fields should be displayed and select the div where it should appear, does it points out to a css class? and if so, which one?

**Comment by smfbigguy** [comment]
Personally I can't find anything but will keep looking.

**Comment by smfbigguy** [comment]
It actually shows for me in the public release of 2.1

**Comment by Sesquipedalian** [comment]
This only happens if you upgraded from a beta version to RC1. (Not supported, remember? 😉)

To fix it manually, you'll need edit the value of the "Show Enclosed Within Text" box of the Gender profile field. Change "generic_icons" to "main_icons", and that should fix it for you.

**Comment by smfbigguy** [comment]
I haven't upgraded my one site yet to the public release. I installed on a new site and it was showing. I guess I will try to upgrade my board later today maybe.

**Comment by lurkalot** [comment]
> main_icons

Thanks, that fixed it for me.

**Comment by smfbigguy** [comment]
> 
> 
> This only happens if you upgraded from a beta version to RC1. (Not supported, remember? 😉)
> 
> To fix it manually, you'll need edit the value of the "Show Enclosed Within Text" box of the Gender profile field. Change "generic_icons" to "main_icons", and that should fix it for you.

What if you go from the last RC on GH to the public release of 2.1 ???

**Comment by MissAllSunday** [comment]
Still not supported but in the ideal world, there shouldn't be any more drastic changes in the DB or the code in general so it would be easier to manually upfrade from an RC version to final.

**Comment by smfbigguy** [comment]
Ok, thank you. :)
