### ISSUE TITLE
Error when you click show online members

### ISSUE THREAD

**Issue by Filiaes** [SimpleMachines/SMF#6187]
#### Description
Error when you click show online members.

Log
```
Art des Fehlers: Generell
8: Array to string conversion
 https://foobar-users.de/index.php?action=who
.../Sources/Who.php (Zeile 454)
```
Backtrace:
```
#0: smf_error_handler()
Called from.../Sources/Who.php on line 454
#1: determineActions()
Called from .../Sources/Who.php on line 210
#2: Who()
Called from .../index.php on line 173
```

### Steps to reproduce
1. When you are logged in click the link "online: x Guests, y Member (z bots)" at the main page
2. Choose show all in the dropdown on the right

### Environment (complete as necessary)
- Version/Git revision: last_commit_8104e43
- Database Type: MySQL
- Database Version: 10.3.23-MariaDB-1:10.3.23+maria~stretch
- PHP Version: 7.1.33

### Additional information/references
Maybe it has something to do with the upgrade process, I had some issues like described in my post [here](https://www.simplemachines.org/community/index.php?action=post;quote=4063764;topic=558451.40;last_msg=4063765) and I am not sure if the conversion in upgrade step 6 has completed successfully

**Comment by albertlast** [comment]
place here:
https://github.com/SimpleMachines/SMF2.1/blob/8104e4328223106289fcb7719f85cb5ce88b1b1a/Sources/Who.php#L452
a 
```var_dump($error_message);```

**Comment by Filiaes** [comment]
Who.php looks now like this:

```
		if (isset($actions['error']))
		{
			loadLanguage('Errors');

			if (isset($txt[$actions['error']]))
				$error_message = str_replace('"', '&quot;', empty($actions['who_error_params']) ? $txt[$actions['error']] : vsprintf($txt[$actions['error']], $actions['who_error_params']));
			elseif ($actions['error'] == 'guest_login')
				$error_message = str_replace('"', '&quot;', $txt['who_guest_login']);
			else
				$error_message = str_replace('"', '&quot;', $actions['error']);
				var_dump($error_message);
			if (!empty($error_message))
				$data[$k] .= ' <span class="main_icons error" title="' . $error_message . '"></span>';
		}
```

Error is the same:

```
Art des Fehlers: Generell
8: Array to string conversion
 https://foobar-users.de/index.php?action=who
 .../Sources/Who.php (Zeile 454)
```
```
#0: smf_error_handler()
Called from.../Sources/Who.php on line 454
#1: determineActions()
Called from.../Sources/Who.php on line 210
#2: Who()
Called from .../index.php on line 173
```

**Comment by albertlast** [comment]
You should had now some kind of debug information,
please post them here.

**Comment by Filiaes** [comment]
Out of nowhere I can't reproduce the error anymore ...

**Comment by Filiaes** [comment]
Now ... here are the debug information from the who page:

`string(114) "Sitzungsverifizierung fehlgeschlagen. Bitte loggen Sie sich aus und danach wieder ein und versuchen Sie es erneut." string(38) "User has been taken to the login page." string(38) "User has been taken to the login page."`

**Comment by albertlast** [comment]
The linked pr should fix the error message reporting,
the next problem in which you would run is the error it self.

**Comment by Filiaes** [comment]
Error in log is the same as above.
New debug message:

`string(49) "Sorry, this section isn't available at this time." string(49) "Sorry, this section isn't available at this time." string(38) "User has been taken to the login page." string(49) "Sorry, this section isn't available at this time." string(49) "Sorry, this section isn't available at this time."`

<img width="512" alt="Screenshot 2020-07-22 at 18 57 38" src="https://user-images.githubusercontent.com/15004960/88205704-75418e00-cc4d-11ea-904d-e7254cd81c8f.png">

**Comment by albertlast** [comment]
This i try to tell you in last message:
you got two problems
first: the real problem
secondly: error message of this problem

The pr fix the last one.

**Comment by Filiaes** [comment]
But the error is still reported in my Log.

changed my who.php like below and uploaded it into Sources, still get the error messages.
```
		if (isset($actions['error']))
		{
			loadLanguage('Errors');

			if (isset($txt[$actions['error']]))
				$error_message = str_replace('"', '&quot;', empty($actions['who_error_params']) ? $txt[$actions['error']] : vsprintf($txt[$actions['error']], $actions['who_error_params']));
			elseif ($actions['error'] == 'guest_login')
				$error_message = str_replace('"', '&quot;', $txt['who_guest_login']);
			else
				$error_message = str_replace('"', '&quot;', $actions['error']);
				// var_dump($error_message);
			if (is_array($error_message))
				$error_message = implode(';',$error_message);
			
			if (!empty($error_message))
				$data[$k] .= ' <span class="main_icons error" title="' . $error_message . '"></span>';
		}
```

**Comment by albertlast** [comment]
Your initial error was this:
```
Art des Fehlers: Generell
8: Array to string conversion
 https://foobar-users.de/index.php?action=who
.../Sources/Who.php (Zeile 454)
````
And this message still appears?

**Comment by Filiaes** [comment]
Message is the same, line changed because I Implemented the changes I guess

```
Art des Fehlers: Generell
8: Array to string conversion
 https://foobar-users.de/index.php?action=who
 .../Sources/Who.php (Zeile 457)
```

**Comment by albertlast** [comment]
So what is line 457 in your Who.php?

**Comment by Filiaes** [comment]
`				$data[$k] .= ' <span class="main_icons error" title="' . $error_message . '"></span>';`

**Comment by albertlast** [comment]
Make no sense to me,
since in line 453 we check if the var is an array, when true we changed to a string...

**Comment by Filiaes** [comment]
Tested and verified everything.
I am sure the changes are implemented into who.php - I attached my who.php which one I downloaded from my smf installlation after I reproduced the error message in the log again - [Who.zip](https://github.com/SimpleMachines/SMF2.1/files/4961568/Who.zip)

I can not reproduce it every time. I guess it also depends on the displayed information at this page but when I try often enough I am able to generate the messages.

<img width="600" alt="Screenshot 2020-07-22 at 20 03 46" src="https://user-images.githubusercontent.com/15004960/88211830-8ba01780-cc56-11ea-99f8-a4687895eec3.png">


Do you need additional information?

**Comment by albertlast** [comment]
Just for the porpuse of testing.
Change this line: 
```$error_message = implode(';',$error_message); ```
to
```$error_message = json_encode($error_message); ```

**Comment by Filiaes** [comment]
Changed line 454 to
`$error_message = json_encode($error_message);`
Same error message still appears

**Comment by albertlast** [comment]
how look like the message?

**Comment by Filiaes** [comment]
exact the same:
```
 Art des Fehlers: Generell
8: Array to string conversion
 https://foobar-users.de/index.php?action=who
 .../Sources/Who.php (Zeile 457)
```
```
#0: smf_error_handler()
Called from.../Sources/Who.php on line 457
#1: determineActions()
Called from .../Sources/Who.php on line 210
#2: Who()
Called from .../index.php on line 173
```

**Comment by albertlast** [comment]
Okay the problem is not $error_message,
the problem is 
```$data[$k] .= ' ....```
since $data[$k] is an array because of line
https://github.com/SimpleMachines/SMF2.1/blob/8104e4328223106289fcb7719f85cb5ce88b1b1a/Sources/Who.php#L439
or similiar line before.
problem is that sometime also a normal string.

So i asked @SychO9  to look into this,
since the idea was introduce by him: https://github.com/SimpleMachines/SMF2.1/commit/38848bbdd975892b673cc99ceb9f028b47386dfa

**Comment by albertlast** [comment]
got you already the chance to test the pr from sych?

**Comment by Filiaes** [comment]
seams that the error messages are gone now ... thanks

**Comment by albertlast** [comment]
dont close the issue,
the issue get closed by the merge process of the pr.
